# Generated by Django 2.2.14 on 2020-07-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loguser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
