# Generated by Django 2.2.14 on 2020-07-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loguser', '0002_auto_20200714_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('college', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='UserLogin',
        ),
    ]
