# Generated by Django 2.2.14 on 2020-07-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loguser', '0003_auto_20200714_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
